class Book {
  String title,
      writer,
      
      image,
      description ;//='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id neque libero. Donec finibus sem viverra, luctus nisi ac, semper enim. Vestibulum in mi feugiat, mattis erat suscipit, fermentum quam. Mauris non urna sed odio congue rhoncus. \nAliquam a dignissim ex. Suspendisse et sem porta, consequat dui et, placerat tortor. Sed elementum nunc a blandit euismod. Cras condimentum faucibus dolor. Etiam interdum egestas sagittis. Aliquam vitae molestie eros. Cras porta felis ac eros pellentesque, sed lobortis mi eleifend. Praesent ut.';
  int pages;
  double rating;

  Book(
      this.title, this.writer,  this.image, this.rating,this.description);
}

final List<Book> books = [
  Book('Clinically Oriented Anatomy', ' Keith L. Moore MSc, PhD, Hon. DSc, FIAC, Arthur F. Dalley II PhD, FAAA, Anne M. R. Agur BSc (OT), MSc, PhD'
      , 'res/Ana_mor.jpg', 4.0,'The world’s most trusted clinically focused anatomy text! \n Renowned for comprehensive coverage, the best-selling Clinically Oriented Anatomy guides students from initial anatomy and foundational science courses through clinical training and practice. The eighth edition reflects significant new information and updates and maintains the highest standards for scientific and clinical accuracy. Comprehensive updates reflect changes in the clinical application of anatomy as well as new imaging technologies, focusing on the anatomy that students need to know. \n Extensively revised “Clinical Blue Boxes” explore the practical applications of anatomy, and helpful icons distinguish the type of clinical information covered in each.\n Clinically relevant anatomy focuses on physical diagnosis, interpretation of diagnostic imaging, and understanding the anatomical basis of emergency medicine and general surgery.\n Insightfully rendered, anatomically accurate illustrations, with updates throughout , make this book an aesthetically rewarding learning resource. Combined with many photographs and medical images, these stunning visuals facilitate comprehension of anatomical concepts and retention of “mental images” of anatomical structures.\n New and updated medical imaging and integrated surface anatomy within each chapter demonstrates the relationship between anatomy, physical examination, and diagnosis.\n Expanded “Overview and Basic Concepts” chapter includes functional systemic anatomy summaries and introduces approaches to studying anatomy, terminology, imaging, and more.\n Inclusion of new sections describing the enteric nervous system (considered by some as a “second brain”) and its unique role in the innervation of the digestive system gives students cutting-edge insight into this significant scientific discovery.\n A more realistic approach to the musculoskeletal system explores the action and use of muscles and muscle groups in daily activities, emphasizing gait and grip.\n “Bottom Line” boxes summarize information to facilitate ongoing review and underscore the big-picture viewpoint.\n Clinical Blue Box animations, case studies, and interactive multiple-choice questions online at thePoint.lww.com facilitate review and self-testing.'),
   Book('Clinically Oriented Anatomy', ' Keith L. Moore MSc, PhD, Hon. DSc, FIAC, Arthur F. Dalley II PhD, FAAA, Anne M. R. Agur BSc (OT), MSc, PhD'
      , 'res/Ana_mor.jpg', 4.0,'The world’s most trusted clinically focused anatomy text! \n Renowned for comprehensive coverage, the best-selling Clinically Oriented Anatomy guides students from initial anatomy and foundational science courses through clinical training and practice. The eighth edition reflects significant new information and updates and maintains the highest standards for scientific and clinical accuracy. Comprehensive updates reflect changes in the clinical application of anatomy as well as new imaging technologies, focusing on the anatomy that students need to know. \n Extensively revised “Clinical Blue Boxes” explore the practical applications of anatomy, and helpful icons distinguish the type of clinical information covered in each.\n Clinically relevant anatomy focuses on physical diagnosis, interpretation of diagnostic imaging, and understanding the anatomical basis of emergency medicine and general surgery.\n Insightfully rendered, anatomically accurate illustrations, with updates throughout , make this book an aesthetically rewarding learning resource. Combined with many photographs and medical images, these stunning visuals facilitate comprehension of anatomical concepts and retention of “mental images” of anatomical structures.\n New and updated medical imaging and integrated surface anatomy within each chapter demonstrates the relationship between anatomy, physical examination, and diagnosis.\n Expanded “Overview and Basic Concepts” chapter includes functional systemic anatomy summaries and introduces approaches to studying anatomy, terminology, imaging, and more.\n Inclusion of new sections describing the enteric nervous system (considered by some as a “second brain”) and its unique role in the innervation of the digestive system gives students cutting-edge insight into this significant scientific discovery.\n A more realistic approach to the musculoskeletal system explores the action and use of muscles and muscle groups in daily activities, emphasizing gait and grip.\n “Bottom Line” boxes summarize information to facilitate ongoing review and underscore the big-picture viewpoint.\n Clinical Blue Box animations, case studies, and interactive multiple-choice questions online at thePoint.lww.com facilitate review and self-testing.'),
   Book('Clinically Oriented Anatomy', ' Keith L. Moore MSc, PhD, Hon. DSc, FIAC, Arthur F. Dalley II PhD, FAAA, Anne M. R. Agur BSc (OT), MSc, PhD'
      , 'res/max_3d.jpeg', 4.0,'The world’s most trusted clinically focused anatomy text! \n Renowned for comprehensive coverage, the best-selling Clinically Oriented Anatomy guides students from initial anatomy and foundational science courses through clinical training and practice. The eighth edition reflects significant new information and updates and maintains the highest standards for scientific and clinical accuracy. Comprehensive updates reflect changes in the clinical application of anatomy as well as new imaging technologies, focusing on the anatomy that students need to know. \n Extensively revised “Clinical Blue Boxes” explore the practical applications of anatomy, and helpful icons distinguish the type of clinical information covered in each.\n Clinically relevant anatomy focuses on physical diagnosis, interpretation of diagnostic imaging, and understanding the anatomical basis of emergency medicine and general surgery.\n Insightfully rendered, anatomically accurate illustrations, with updates throughout , make this book an aesthetically rewarding learning resource. Combined with many photographs and medical images, these stunning visuals facilitate comprehension of anatomical concepts and retention of “mental images” of anatomical structures.\n New and updated medical imaging and integrated surface anatomy within each chapter demonstrates the relationship between anatomy, physical examination, and diagnosis.\n Expanded “Overview and Basic Concepts” chapter includes functional systemic anatomy summaries and introduces approaches to studying anatomy, terminology, imaging, and more.\n Inclusion of new sections describing the enteric nervous system (considered by some as a “second brain”) and its unique role in the innervation of the digestive system gives students cutting-edge insight into this significant scientific discovery.\n A more realistic approach to the musculoskeletal system explores the action and use of muscles and muscle groups in daily activities, emphasizing gait and grip.\n “Bottom Line” boxes summarize information to facilitate ongoing review and underscore the big-picture viewpoint.\n Clinical Blue Box animations, case studies, and interactive multiple-choice questions online at thePoint.lww.com facilitate review and self-testing.'),
 
];
final List<Book> books_phy = [
  Book('CorelDraw untuk Tingkat Pemula Sampai Mahir', 'Jubilee Enterprise'
      , 'res/sketchup.jpeg', 3.5,'vbcbvcvbxvxcvxcvxcvxcvbLorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id neque libero. Donec finibus sem viverra, luctus nisi ac, semper enim. Vestibulum in mi feugiat, mattis erat suscipit, fermentum quam. Mauris non urna sed odio congue rhoncus. \nAliquam a dignissim ex. Suspendisse et sem porta, consequat dui et, placerat tortor. Sed elementum nunc a blandit euismod. Cras condimentum faucibus dolor. Etiam interdum egestas sagittis. Aliquam vitae molestie eros. Cras porta felis ac eros pellentesque, sed lobortis mi eleifend. Praesent ut. \n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id neque libero. Donec finibus sem viverra, luctus nisi ac, semper enim. Vestibulum in mi feugiat, mattis erat suscipit, fermentum quam. Mauris non urna sed odio congue rhoncus. \nAliquam a dignissim ex. Suspendisse et sem porta, consequat dui et, placerat tortor. Sed elementum nunc a blandit euismod. Cras condimentum faucibus dolor. Etiam interdum egestas sagittis. Aliquam vitae molestie eros. Cras porta felis ac eros pellentesque, sed lobortis mi eleifend. Praesent ut.'),
   Book('CorelDraw untuk Tingkat Pemula Sampai Mahir', 'Jubilee Enterprise'
      , 'res/corel.jpg', 3.5,'vbcbvcvbxvxcvxcvxcvxcvbLorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id neque libero. Donec finibus sem viverra, luctus nisi ac, semper enim. Vestibulum in mi feugiat, mattis erat suscipit, fermentum quam. Mauris non urna sed odio congue rhoncus. \nAliquam a dignissim ex. Suspendisse et sem porta, consequat dui et, placerat tortor. Sed elementum nunc a blandit euismod. Cras condimentum faucibus dolor. Etiam interdum egestas sagittis. Aliquam vitae molestie eros. Cras porta felis ac eros pellentesque, sed lobortis mi eleifend. Praesent ut. \n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id neque libero. Donec finibus sem viverra, luctus nisi ac, semper enim. Vestibulum in mi feugiat, mattis erat suscipit, fermentum quam. Mauris non urna sed odio congue rhoncus. \nAliquam a dignissim ex. Suspendisse et sem porta, consequat dui et, placerat tortor. Sed elementum nunc a blandit euismod. Cras condimentum faucibus dolor. Etiam interdum egestas sagittis. Aliquam vitae molestie eros. Cras porta felis ac eros pellentesque, sed lobortis mi eleifend. Praesent ut.'),
   Book('CorelDraw untuk Tingkat Pemula Sampai Mahir', 'Jubilee Enterprise'
      , 'res/photoshop.jpg', 3.5,'vbcbvcvbxvxcvxcvxcvxcvbLorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id neque libero. Donec finibus sem viverra, luctus nisi ac, semper enim. Vestibulum in mi feugiat, mattis erat suscipit, fermentum quam. Mauris non urna sed odio congue rhoncus. \nAliquam a dignissim ex. Suspendisse et sem porta, consequat dui et, placerat tortor. Sed elementum nunc a blandit euismod. Cras condimentum faucibus dolor. Etiam interdum egestas sagittis. Aliquam vitae molestie eros. Cras porta felis ac eros pellentesque, sed lobortis mi eleifend. Praesent ut. \n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id neque libero. Donec finibus sem viverra, luctus nisi ac, semper enim. Vestibulum in mi feugiat, mattis erat suscipit, fermentum quam. Mauris non urna sed odio congue rhoncus. \nAliquam a dignissim ex. Suspendisse et sem porta, consequat dui et, placerat tortor. Sed elementum nunc a blandit euismod. Cras condimentum faucibus dolor. Etiam interdum egestas sagittis. Aliquam vitae molestie eros. Cras porta felis ac eros pellentesque, sed lobortis mi eleifend. Praesent ut.'),
 
];

